// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs) during `cargo build` step. Do not edit this file manually.

export type Control = { name: string, cpp_type: string, id: number, state: ControlState, configuration: ControlType, };

export type ControlType = { "Bool": ControlBool } | { "Slider": ControlSlider } | { "Menu": ControlMenu };

export type ControlState = { is_disabled: boolean, is_inactive: boolean, };

export type ControlBool = { default: number, value: number, };

export type ControlSlider = { default: number, value: number, step: number, max: number, min: number, };

export type ControlMenu = { default: number, value: number, options: Array<ControlOption>, };

export type ControlOption = { name: string, value: number, };

export type VideoEncodeType = "H264" | "H265" | "MJPG" | "RGB" | { "UNKNOWN": string } | "YUYV";

export type Format = { encode: VideoEncodeType, sizes: Array<Size>, };

export type Size = { width: number, height: number, intervals: Array<FrameInterval>, };

export type FrameInterval = { numerator: number, denominator: number, };

export type VideoSourceType = { "Gst": VideoSourceGst } | { "Local": VideoSourceLocal } | { "Onvif": VideoSourceOnvif } | { "Redirect": VideoSourceRedirect };

export type VideoSourceLocalType = { "Unknown": string } | { "Usb": string } | { "LegacyRpiCam": string };

export type VideoSourceLocal = { name: string, device_path: string, type: VideoSourceLocalType, };

export type VideoSourceGstType = { "Local": VideoSourceLocal } | { "Fake": string } | { "QR": string };

export type VideoSourceGst = { name: string, source: VideoSourceGstType, };

export type VideoSourceOnvifType = { "Onvif": string };

export type VideoSourceOnvif = { name: string, source: VideoSourceOnvifType, manufacturer: string, model: string, firmware_version: string, serial_number: string, hardware_id: string, };

export type OnvifDeviceInformation = { manufacturer: string, model: string, firmware_version: string, serial_number: string, hardware_id: string, };

export type VideoSourceRedirectType = { "Redirect": string };

export type VideoSourceRedirect = { name: string, source: VideoSourceRedirectType, };

export type VideoCaptureConfiguration = { encode: VideoEncodeType, height: number, width: number, frame_interval: FrameInterval, };

export type RedirectCaptureConfiguration = Record<string, never>;

export type CaptureConfiguration = { "type": "video" } & VideoCaptureConfiguration | { "type": "redirect" } & RedirectCaptureConfiguration;

export type ExtendedConfiguration = { thermal: boolean, disable_mavlink: boolean, disable_zenoh: boolean, disable_thumbnails: boolean, };

export type StreamInformation = { endpoints: Array<string>, configuration: CaptureConfiguration, extended_configuration: ExtendedConfiguration | null, };

export type StreamStatus = { id: string, running: boolean, error: string | null, video_and_stream: VideoAndStreamInformation, mavlink: MavlinkComponent | null, };

export type MavlinkComponent = { system_id: number, component_id: number, };

export type VideoAndStreamInformation = { name: string, stream_information: StreamInformation, video_source: VideoSourceType, };

export type ApiVideoSource = { name: string, source: string, formats: Array<Format>, controls: Array<Control>, blocked: boolean, };

export type V4lControl = { device: string, v4l_id: number, value: number, };

export type PostStream = { name: string, source: string, stream_information: StreamInformation, };

export type RemoveStream = { name: string, };

export type BlockSource = { source_string: string, };

export type UnblockSource = { source_string: string, };

export type ResetSettings = { all: boolean | null, };

export type ResetCameraControls = { device: string, };

export type XmlFileRequest = { file: string, };

export type SdpFileRequest = { source: string, };

export type ThumbnailFileRequest = { source: string, 
/**
 * The Quality level (a percentage value as an integer between 1 and 100) is inversely proportional to JPEG compression level, which means the higher, the best.
 */
quality: number | null, 
/**
 * Target height of the thumbnail. The value should be an integer between 1 and 1080 (because of memory constraints).
 */
target_height: number | null, };

export type Info = { 
/**
 * Name of the program
 */
name: string, 
/**
 * Version/tag
 */
version: string, 
/**
 * Git SHA
 */
sha: string, build_date: string, 
/**
 * Authors name
 */
authors: string, 
/**
 * Unstable field for custom development
 */
development: Development, };

export type Development = { number_of_tasks: number, };

export type AuthenticateOnvifDeviceRequest = { 
/**
 * Onvif Device UUID, obtained via `/onvif/devices` get request
 */
device_uuid: string, 
/**
 * Username for the Onvif Device
 */
username: string, 
/**
 * Password for the Onvif Device
 */
password: string, };

export type UnauthenticateOnvifDeviceRequest = { 
/**
 * Onvif Device UUID, obtained via `/onvif/devices` get request
 */
device_uuid: string, };

export type OnvifDevice = { uuid: string, ip: string, types: Array<string>, hardware: string | null, name: string | null, urls: Array<string>, };