// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs) during `cargo build` step. Do not edit this file manually.

export type Message = { "type": "question", "content": Question } | { "type": "answer", "content": Answer } | { "type": "negotiation", "content": Negotiation };

export type Answer = { "type": "peerId", "content": PeerIdAnswer } | { "type": "availableStreams", "content": Array<Stream> } | { "type": "startSession", "content": BindAnswer };

export type Question = { "type": "peerId" } | { "type": "availableStreams" } | { "type": "startSession", "content": BindOffer } | { "type": "endSession", "content": EndSessionQuestion };

export type Negotiation = { "type": "mediaNegotiation", "content": MediaNegotiation } | { "type": "iceNegotiation", "content": IceNegotiation };

export type BindOffer = { 
/**
 * each tab in the browser
 */
consumer_id: string, 
/**
 * each stream/camera
 */
producer_id: string, };

export type BindAnswer = { 
/**
 * each tab in the browser
 */
consumer_id: string, 
/**
 * each stream/camera
 */
producer_id: string, 
/**
 * associated session
 */
session_id: string, };

export type PeerIdAnswer = { id: string, };

export type Stream = { id: string, name: string, encode: string | null, height: number | null, width: number | null, interval: string | null, source: string | null, created: string | null, };

export type IceNegotiation = { ice: RTCIceCandidateInit, 
/**
 * each tab in the browser
 */
consumer_id: string, 
/**
 * each stream/camera
 */
producer_id: string, 
/**
 * associated session
 */
session_id: string, };

export type MediaNegotiation = { sdp: RTCSessionDescription, 
/**
 * each tab in the browser
 */
consumer_id: string, 
/**
 * each stream/camera
 */
producer_id: string, 
/**
 * associated session
 */
session_id: string, };

export type EndSessionQuestion = { reason: string, 
/**
 * each tab in the browser
 */
consumer_id: string, 
/**
 * each stream/camera
 */
producer_id: string, 
/**
 * associated session
 */
session_id: string, };