use std::{fs, io::Write, path::Path};

use regex::Regex;
use ts_rs::TS;

use mcm_api::v1::{controls::*, server::*, signalling::*, stream::*, video::*};

fn generate_bindings(types: &[String]) -> String {
    // Remove all typescript "import type" because all types are going to live in the same typescript file
    let bindings = types.join("\n\n");
    let re = Regex::new(r"(?m)^import type .*\n")
        .expect("Regex for stripping import-type lines must be valid");
    let bindings = re.replace_all(bindings.as_str(), "").to_string();

    // Replace all notices by a custom one
    let re = Regex::new(r"(?m)^// This file was generated by .*\n\n")
        .expect("Regex for stripping ts-rs header must be valid");
    let mut bindings = re.replace_all(bindings.as_str(), "").to_string();
    let custom_notice_str = "// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs) during `cargo build` step. Do not edit this file manually.\n\n";
    bindings.insert_str(0, custom_notice_str);

    bindings
}

fn write_bindings(output_dir: &Path, filename: &str, bindings: &str) {
    if !output_dir.exists() {
        std::fs::create_dir_all(output_dir).expect("Failed to create bindings output directory");
    }
    let bindings_file_path = output_dir.join(Path::new(filename));
    let mut bindings_file =
        fs::File::create(bindings_file_path).expect("Failed to create bindings file");
    bindings_file
        .write_all(bindings.as_bytes())
        .expect("Failed to write bindings file");
}

fn main() {
    let output_dir = Path::new("./frontend/bindings/v1/");

    // -- Signalling protocol bindings (backward-compatible file) --
    let signalling_types = [
        Message::export_to_string().expect("Failed to export Message to TypeScript"),
        Answer::export_to_string().expect("Failed to export Answer to TypeScript"),
        Question::export_to_string().expect("Failed to export Question to TypeScript"),
        Negotiation::export_to_string().expect("Failed to export Negotiation to TypeScript"),
        BindOffer::export_to_string().expect("Failed to export BindOffer to TypeScript"),
        BindAnswer::export_to_string().expect("Failed to export BindAnswer to TypeScript"),
        PeerIdAnswer::export_to_string().expect("Failed to export PeerIdAnswer to TypeScript"),
        Stream::export_to_string().expect("Failed to export Stream to TypeScript"),
        IceNegotiation::export_to_string().expect("Failed to export IceNegotiation to TypeScript"),
        MediaNegotiation::export_to_string()
            .expect("Failed to export MediaNegotiation to TypeScript"),
        EndSessionQuestion::export_to_string()
            .expect("Failed to export EndSessionQuestion to TypeScript"),
    ];
    let signalling_bindings = generate_bindings(&signalling_types);
    write_bindings(output_dir, "signalling_protocol.d.ts", &signalling_bindings);

    // -- REST API bindings --
    let api_types = [
        // Controls
        Control::export_to_string().expect("Failed to export Control to TypeScript"),
        ControlType::export_to_string().expect("Failed to export ControlType to TypeScript"),
        ControlState::export_to_string().expect("Failed to export ControlState to TypeScript"),
        ControlBool::export_to_string().expect("Failed to export ControlBool to TypeScript"),
        ControlSlider::export_to_string().expect("Failed to export ControlSlider to TypeScript"),
        ControlMenu::export_to_string().expect("Failed to export ControlMenu to TypeScript"),
        ControlOption::export_to_string().expect("Failed to export ControlOption to TypeScript"),
        // Video types
        VideoEncodeType::export_to_string()
            .expect("Failed to export VideoEncodeType to TypeScript"),
        Format::export_to_string().expect("Failed to export Format to TypeScript"),
        Size::export_to_string().expect("Failed to export Size to TypeScript"),
        FrameInterval::export_to_string().expect("Failed to export FrameInterval to TypeScript"),
        VideoSourceType::export_to_string()
            .expect("Failed to export VideoSourceType to TypeScript"),
        VideoSourceLocalType::export_to_string()
            .expect("Failed to export VideoSourceLocalType to TypeScript"),
        VideoSourceLocal::export_to_string()
            .expect("Failed to export VideoSourceLocal to TypeScript"),
        VideoSourceGstType::export_to_string()
            .expect("Failed to export VideoSourceGstType to TypeScript"),
        VideoSourceGst::export_to_string().expect("Failed to export VideoSourceGst to TypeScript"),
        VideoSourceOnvifType::export_to_string()
            .expect("Failed to export VideoSourceOnvifType to TypeScript"),
        VideoSourceOnvif::export_to_string()
            .expect("Failed to export VideoSourceOnvif to TypeScript"),
        OnvifDeviceInformation::export_to_string()
            .expect("Failed to export OnvifDeviceInformation to TypeScript"),
        VideoSourceRedirectType::export_to_string()
            .expect("Failed to export VideoSourceRedirectType to TypeScript"),
        VideoSourceRedirect::export_to_string()
            .expect("Failed to export VideoSourceRedirect to TypeScript"),
        // Stream types
        VideoCaptureConfiguration::export_to_string()
            .expect("Failed to export VideoCaptureConfiguration to TypeScript"),
        RedirectCaptureConfiguration::export_to_string()
            .expect("Failed to export RedirectCaptureConfiguration to TypeScript"),
        CaptureConfiguration::export_to_string()
            .expect("Failed to export CaptureConfiguration to TypeScript"),
        ExtendedConfiguration::export_to_string()
            .expect("Failed to export ExtendedConfiguration to TypeScript"),
        StreamInformation::export_to_string()
            .expect("Failed to export StreamInformation to TypeScript"),
        StreamStatus::export_to_string().expect("Failed to export StreamStatus to TypeScript"),
        MavlinkComponent::export_to_string()
            .expect("Failed to export MavlinkComponent to TypeScript"),
        VideoAndStreamInformation::export_to_string()
            .expect("Failed to export VideoAndStreamInformation to TypeScript"),
        // Server / API types
        ApiVideoSource::export_to_string().expect("Failed to export ApiVideoSource to TypeScript"),
        V4lControl::export_to_string().expect("Failed to export V4lControl to TypeScript"),
        PostStream::export_to_string().expect("Failed to export PostStream to TypeScript"),
        RemoveStream::export_to_string().expect("Failed to export RemoveStream to TypeScript"),
        BlockSource::export_to_string().expect("Failed to export BlockSource to TypeScript"),
        UnblockSource::export_to_string().expect("Failed to export UnblockSource to TypeScript"),
        ResetSettings::export_to_string().expect("Failed to export ResetSettings to TypeScript"),
        ResetCameraControls::export_to_string()
            .expect("Failed to export ResetCameraControls to TypeScript"),
        XmlFileRequest::export_to_string().expect("Failed to export XmlFileRequest to TypeScript"),
        SdpFileRequest::export_to_string().expect("Failed to export SdpFileRequest to TypeScript"),
        ThumbnailFileRequest::export_to_string()
            .expect("Failed to export ThumbnailFileRequest to TypeScript"),
        Info::export_to_string().expect("Failed to export Info to TypeScript"),
        Development::export_to_string().expect("Failed to export Development to TypeScript"),
        AuthenticateOnvifDeviceRequest::export_to_string()
            .expect("Failed to export AuthenticateOnvifDeviceRequest to TypeScript"),
        UnauthenticateOnvifDeviceRequest::export_to_string()
            .expect("Failed to export UnauthenticateOnvifDeviceRequest to TypeScript"),
        OnvifDevice::export_to_string().expect("Failed to export OnvifDevice to TypeScript"),
    ];
    let api_bindings = generate_bindings(&api_types);
    write_bindings(output_dir, "api.d.ts", &api_bindings);
}
