use std::{fs, io::Write, path::Path};

use regex::Regex;
use ts_rs::TS;

use mcm_api::v1::{controls::*, server::*, signalling::*, stats::*, stream::*, video::*};

fn generate_bindings(types: &[String]) -> String {
    // Remove all typescript "import type" because all types are going to live in the same typescript file
    let bindings = types.join("\n\n");
    let re = Regex::new(r"(?m)^import type .*\n").unwrap();
    let bindings = re.replace_all(bindings.as_str(), "").to_string();

    // Replace all notices by a custom one
    let re = Regex::new(r"(?m)^// This file was generated by .*\n\n").unwrap();
    let mut bindings = re.replace_all(bindings.as_str(), "").to_string();
    let custom_notice_str = "// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs) during `cargo build` step. Do not edit this file manually.\n\n";
    bindings.insert_str(0, custom_notice_str);

    bindings
}

fn write_bindings(output_dir: &Path, filename: &str, bindings: &str) {
    if !output_dir.exists() {
        std::fs::create_dir_all(output_dir).unwrap();
    }
    let bindings_file_path = output_dir.join(Path::new(filename));
    let mut bindings_file = fs::File::create(bindings_file_path).unwrap();
    bindings_file.write_all(bindings.as_bytes()).unwrap();
}

fn main() {
    let output_dir = Path::new("./frontend/bindings/v1/");

    // -- Signalling protocol bindings (backward-compatible file) --
    let signalling_types = [
        Message::export_to_string().unwrap(),
        Answer::export_to_string().unwrap(),
        Question::export_to_string().unwrap(),
        Negotiation::export_to_string().unwrap(),
        BindOffer::export_to_string().unwrap(),
        BindAnswer::export_to_string().unwrap(),
        PeerIdAnswer::export_to_string().unwrap(),
        Stream::export_to_string().unwrap(),
        IceNegotiation::export_to_string().unwrap(),
        MediaNegotiation::export_to_string().unwrap(),
        EndSessionQuestion::export_to_string().unwrap(),
    ];
    let signalling_bindings = generate_bindings(&signalling_types);
    write_bindings(output_dir, "signalling_protocol.d.ts", &signalling_bindings);

    // -- REST API bindings --
    let api_types = [
        // Controls
        Control::export_to_string().unwrap(),
        ControlType::export_to_string().unwrap(),
        ControlState::export_to_string().unwrap(),
        ControlBool::export_to_string().unwrap(),
        ControlSlider::export_to_string().unwrap(),
        ControlMenu::export_to_string().unwrap(),
        ControlOption::export_to_string().unwrap(),
        // Video types
        VideoEncodeType::export_to_string().unwrap(),
        Format::export_to_string().unwrap(),
        Size::export_to_string().unwrap(),
        FrameInterval::export_to_string().unwrap(),
        VideoSourceType::export_to_string().unwrap(),
        VideoSourceLocalType::export_to_string().unwrap(),
        VideoSourceLocal::export_to_string().unwrap(),
        VideoSourceGstType::export_to_string().unwrap(),
        VideoSourceGst::export_to_string().unwrap(),
        VideoSourceOnvifType::export_to_string().unwrap(),
        VideoSourceOnvif::export_to_string().unwrap(),
        OnvifDeviceInformation::export_to_string().unwrap(),
        VideoSourceRedirectType::export_to_string().unwrap(),
        VideoSourceRedirect::export_to_string().unwrap(),
        // Stream types
        VideoCaptureConfiguration::export_to_string().unwrap(),
        RedirectCaptureConfiguration::export_to_string().unwrap(),
        CaptureConfiguration::export_to_string().unwrap(),
        ExtendedConfiguration::export_to_string().unwrap(),
        StreamInformation::export_to_string().unwrap(),
        StreamStatus::export_to_string().unwrap(),
        MavlinkComponent::export_to_string().unwrap(),
        VideoAndStreamInformation::export_to_string().unwrap(),
        // Server / API types
        ApiVideoSource::export_to_string().unwrap(),
        V4lControl::export_to_string().unwrap(),
        PostStream::export_to_string().unwrap(),
        RemoveStream::export_to_string().unwrap(),
        BlockSource::export_to_string().unwrap(),
        UnblockSource::export_to_string().unwrap(),
        ResetSettings::export_to_string().unwrap(),
        ResetCameraControls::export_to_string().unwrap(),
        XmlFileRequest::export_to_string().unwrap(),
        SdpFileRequest::export_to_string().unwrap(),
        ThumbnailFileRequest::export_to_string().unwrap(),
        Info::export_to_string().unwrap(),
        Development::export_to_string().unwrap(),
        AuthenticateOnvifDeviceRequest::export_to_string().unwrap(),
        UnauthenticateOnvifDeviceRequest::export_to_string().unwrap(),
        OnvifDevice::export_to_string().unwrap(),
        // Stats / Pipeline Analysis types — new hierarchical model
        StatsLevel::export_to_string().unwrap(),
        RawRecord::export_to_string().unwrap(),
        AccumulatorSnapshot::export_to_string().unwrap(),
        Distribution::export_to_string().unwrap(),
        DistributionSnapshot::export_to_string().unwrap(),
        SystemDistribution::export_to_string().unwrap(),
        SystemSnapshot::export_to_string().unwrap(),
        RestartSnapshot::export_to_string().unwrap(),
        HealthStatus::export_to_string().unwrap(),
        IssueKind::export_to_string().unwrap(),
        CausalConfidence::export_to_string().unwrap(),
        RootCauseCandidate::export_to_string().unwrap(),
        ThreadBottleneck::export_to_string().unwrap(),
        PipelineSummary::export_to_string().unwrap(),
        // New hierarchical types
        StreamsSnapshot::export_to_string().unwrap(),
        FleetStats::export_to_string().unwrap(),
        StreamSnapshot::export_to_string().unwrap(),
        StreamStats::export_to_string().unwrap(),
        PipelineSnapshot::export_to_string().unwrap(),
        PipelineStats::export_to_string().unwrap(),
        PipelineConnection::export_to_string().unwrap(),
        ThreadSummary::export_to_string().unwrap(),
        ThreadStats::export_to_string().unwrap(),
        ThreadConnection::export_to_string().unwrap(),
        ElementSnapshot::export_to_string().unwrap(),
        ElementStats::export_to_string().unwrap(),
        ElementConnection::export_to_string().unwrap(),
        PadDirection::export_to_string().unwrap(),
        PadSnapshot::export_to_string().unwrap(),
        PadStats::export_to_string().unwrap(),
        PadConnection::export_to_string().unwrap(),
        SetLevelRequest::export_to_string().unwrap(),
        SetWindowSizeRequest::export_to_string().unwrap(),
        ElementProperty::export_to_string().unwrap(),
        QueueStats::export_to_string().unwrap(),
    ];
    let api_bindings = generate_bindings(&api_types);
    write_bindings(output_dir, "api.d.ts", &api_bindings);
}
